### PR TITLE
lmsw/todolist-app Branch Created & Initial Commit

### PR DESCRIPTION
**Pull request by LaTonia-Mertica**
Good Day,

Now I need to conquer this completed feature per the assignment instructions - wish me luck.

Talk soon @Tyler-Toro!

### CODE REVIEW

**Comment by LaTonia-Mertica** [comment]
Hello @Tyler-Toro - such a code eventful day ... 

I considered adding a readme to my todo list and decided I can later if still feel necessary. It basically would state what the app is, how it works, have some quirky insight into my personality, and list next steps as:

- tightening up the widths for better precision between the input fields and submits;
- add a help/tip for the never todo to explain (for those who don't know) philosophy at core of releasing things into the ether to get beyond them; 
- code a more appeasing color scheme for the todo page submits 

Drafting a readme may be beneficial later if I add the todolist app/project to my repo/digital portfolio.

Anyhoot, hope pre-election Monday has been kind to you. Talk soon ...

**Comment by LaTonia-Mertica** [comment]
Hey There @Tyler-Toro,

Think I'm good on this branch for a bit unless something unexpected comes up ... thanks, talk soon ...

**Comment by LaTonia-Mertica** [comment]
I Swear,

I can't help it. An idea pops in my mental and I rush to try it ... thinking this project is done DONE now ... much happier with the overall design and general functionality ...

**Comment by LaTonia-Mertica** [comment]
not sure reasons there was commit/push activity ... I was poking around time to time as we worked through stuff this evening but didn't actually change anything ... although, now that I think of it, I did try to do some more styling ... inline hover which apparently is a no-no ... anyhoot ... thanks for being awesome you ... talk soon

**Comment by LaTonia-Mertica** [comment]
Now I can see adding the todo list app to my portfolio - toss confetti time ....

**Review by Tyler-Toro — APPROVED** [review]
Adding this to main

**Pull request merged**
